# Generated by Django 3.0.6 on 2020-05-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pointA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point_a', to='taxi.Point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='pointB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point_b', to='taxi.Point'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trip2Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='taxi.UserProfile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.UserProfile')),
            ],
        ),
    ]
