# Generated by Django 3.0.6 on 2020-05-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20200508_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='pointA',
            new_name='point_a',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='pointB',
            new_name='point_b',
        ),
    ]
