# Generated by Django 3.0.6 on 2020-05-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20200508_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauth',
            name='secret',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip2passenger',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Trip'),
        ),
    ]
