# Generated by Django 3.0.6 on 2020-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_auto_20200508_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
