# Generated by Django 3.0.6 on 2020-05-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_trip_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.UserProfile')),
            ],
        ),
    ]
