# Generated by Django 3.0.6 on 2020-11-14 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0013_auto_20200508_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(default='21:00:00'),
        ),
        migrations.AlterField(
            model_name='region2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
